In [17]:
import numpy as np

1.Create a 3x3 array that contains a diagonal of nines.


In [18]:
np.diag([9,9,9])

array([[9, 0, 0],
       [0, 9, 0],
       [0, 0, 9]])

2. Create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive) and use Boolean indexing to pick out the values that are within 1/2 standard deviations of the mean.


In [28]:
a = np.arange(2,33,2).reshape(4,4)
mean = a.mean()
std=a.std()
values = a[(a<(mean+std)) & (a>(mean-std))]
values

array([ 8, 10, 12, 14, 16, 18, 20, 22, 24, 26])

 3. Create a 9x9 array that contains only zero of type int.


In [20]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

4. Ask the user for a number n. Then, use broadcasting to create a n x n ndarray that has its first column full of ones, its second column full of twos, its third column full of threes, etc…

In [21]:
n = int(input("Enter the array size"))
a = np.arange(1,n+1).reshape(1,n)
arr = np.ones((n,1))*a
arr

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])